# Generated by Django 3.1.2 on 2020-10-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_posts',
            name='dt',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='msg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='pic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='post_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user_posts',
            name='tm',
            field=models.CharField(max_length=500),
        ),
    ]
